name: '522'
channels:
  - conda-forge
dependencies:
  - python=3
  - pandas
  - jupyterlab
  - altair
  - vegafusion[version='>=2.0.3']
  - vl-convert-python[version='>=1.8.0']
  - pyarrow
  - pip:
      - ucimlrepo==0.0.7
