name: '522'
channels:
  - conda-forge
dependencies:
  - python=3
  - pandas
  - jupyterlab
  - altair
  - vegafusion[version='>=2.0.3']
  - vl-convert-python[version='>=1.8.0']
  - pyarrow
  - matplotlib==3.10.7
  - numpy==2.3.5
  - pandas==2.3.3
  - scikit_learn==1.7.2
  - seaborn==0.13.2
  - pip:
      - ucimlrepo==0.0.7
